version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: resource-sharing-app
    ports:
      - "${PORT:-3000}:3000"
    volumes:
      - sqlite_data:/app/prisma

    environment:
      DATABASE_URL: file:/app/prisma/dev.db
      PORT: 3000
      NODE_ENV: production

    restart: unless-stopped

volumes:
  sqlite_data:
